branches:
    only:
        - master
        - develop
language: python
python:
    - "2.7"
    - "3.4"
before_install:
    - make bootstrap-dev
    - pip install python-coveralls
script:
    - make test
after_success:
    - coveralls
